tdevPages:
    - path: ../inf-trb
      apiMode: 'api'
      managed: 'fully'
    - path: ../inf-shu
      apiMode: 'api'
      managed: 'fully'
    - path: ../inf-gls
      apiMode: 'api'
      managed: 'fully'
    - path: ../ef-2028
      apiMode: 'api'
      managed: 'fully'
    - path: ../sdg-teaching-website
      apiMode: 'indexedDb'
      managed: 'fully'
    - path: ../ict
      apiMode: 'indexedDb'
      managed: 'fully'
    - path: ../../lebalz/teaching-inf
      apiMode: 'api'
      managed: 'none'
