backend:
    name: github
    branch: main
    repo: GBSL-Informatik/teaching-dev

# These lines should *not* be indented
media_folder: 'static/img' # Media files will be stored in the repo under static/images/uploads
# media_folder: "{{media_folder_path}}/{{media_folder_relative_path}}"
public_folder: '/img/' # The src attribute for uploaded media will begin with /images/uploads

collections:
    - name: docs
      label: 'docs'
      label_singular: 'doc'
      folder: docs
      identifier_field: title
      extension: mdx
      format: frontmatter
      create: true
      nested:
          depth: 100 # max depth to show in the collection tree
          summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
      fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      # adding a meta object with a path property allows editing the path of entries
      # moving an existing entry will move the entire sub tree of the entry to the new location
      meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
