import path from 'path';
import fs from 'fs/promises';
import { loadMaterialConfig, pathExists, saveMaterialConfig } from './material_helpers';
import minimist from 'minimist';
import { exit } from 'process';
import crypto from 'node:crypto';

const repoRoot = path.resolve(__dirname, '..');
process.chdir(repoRoot);

const configs = loadMaterialConfig();
const currentKlasses = Object.keys(configs);
const argv = minimist(process.argv.slice(2));

if (argv.help) {
    console.log(`
yarn run add_class [className]

examples:

yarn run addClass 30Gx              // adds a new class to 'versioned_docs', 'versioned_sidebar' and to 'material.config.yaml'
yarn run addClass 30Ga,30Gx
yarn run addClass "30Ga, 30Gx"
`);
    exit(0);
}

const newKlasses = (argv._[0] ?? '')
    .split(',')
    .map((k) => k.trim())
    .filter((k) => k && !currentKlasses.includes(k))
    .sort();

const homeTemplate = (klass: string): string => {
    return `---
sidebar_position: 0.1
sidebar_label: ${klass}
page_id: ${crypto.randomUUID()}
---

# ${klass}
`;
};

const main = async (): Promise<void> => {
    const versionedSidebarsPath = path.join(repoRoot, 'versioned_sidebars');
    if (!(await pathExists(versionedSidebarsPath))) {
        await fs.mkdir(versionedSidebarsPath, { recursive: true });
    }

    for (const klass of newKlasses) {
        const versionedDocsPath = path.join(repoRoot, 'versioned_docs', `version-${klass}`);
        if (!(await pathExists(versionedDocsPath))) {
            await fs.mkdir(versionedDocsPath, { recursive: true });
        }
        const sidebarPath = path.join(versionedSidebarsPath, `version-${klass}-sidebars.json`);
        if (!(await pathExists(sidebarPath))) {
            await fs.writeFile(
                sidebarPath,
                JSON.stringify({ sidebar: [{ type: 'autogenerated', dirName: '.' }] }, null, 2)
            );
        }
        const homePath = path.join(versionedDocsPath, 'home.mdx');
        if (!(await pathExists(homePath))) {
            await fs.writeFile(homePath, homeTemplate(klass));
        }
        configs[klass] = [];
    }
    const hasVersions = await pathExists(path.join(repoRoot, 'versions.json'));
    const currentVersions = await (hasVersions
        ? fs
              .readFile(path.join(repoRoot, 'versions.json'), 'utf-8')
              .then((data) => JSON.parse(data) as string[])
        : Promise.resolve([]));
    const newVersions = [...new Set([...currentVersions, ...newKlasses].sort())];
    await fs.writeFile(path.join(repoRoot, 'versions.json'), JSON.stringify(newVersions, null, 2));
    saveMaterialConfig(configs);

    console.log('✅ Added new classes:', newKlasses.join(', '), 'Edit your siteConfig.ts accordingly');
};

main().catch((e: Error) => {
    console.error(e);
    process.exit(1);
});
